//! Cross-language golden-vector conformance suite.
//!
//! `testdata/proto/` (top-level, so the C# plugin suite reaches it by
//! relative path without entering a Rust crate) holds the committed byte
//! vectors described by `testdata/proto/manifest.json`. The normal tests
//! here load those exact files and assert:
//!
//! - `.raw` vectors (type + payload + CRC-16 LE) parse to the expected
//!   typed [`Packet`] and re-encode byte-identically;
//! - `.wire` vectors (COBS + trailing `0x00` delimiter) decode through
//!   COBS + parse to the same packet and re-encode byte-identically;
//! - negative vectors fail with exactly the expected error class;
//! - the resync stream recovers exactly the embedded valid packets.
//!
//! The manifest itself is generated by the same tables that drive the
//! tests ([`all_files`]) and asserted byte-identical to the on-disk copy,
//! so manifest.json and the expectations below cannot drift apart — the
//! tables *are* the manifest. That also keeps `proto` free of a JSON
//! dev-dependency.
//!
//! Regeneration: only via `just golden-regen`, which wraps
//! `cargo test -p proto --test golden_vectors -- --ignored regen`. The
//! [`regen`] test rewrites every file under `testdata/proto/`
//! deterministically — no wall clock, no randomness, fixed patterns and
//! seeds only — so two consecutive runs are byte-identical.

use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};

use proto::packet::{
    self, Button, Packet, PacketType, Parsed, PressKind, FRAME_PAYLOAD_LEN, MAX_RAW_LEN,
    MAX_WIRE_LEN, PANEL_HEIGHT, PANEL_WIDTH, PROTOCOL_VERSION,
};
use proto::{cobs, crc};

// Vector inputs. Changing anything here changes the golden files — regenerate
// via `just golden-regen`, and on purpose: a regen that moves bytes is a
// protocol change.

/// Brightness set-point carried by the `brightness` vector.
const BRIGHTNESS_VALUE: u8 = 200;

/// Firmware version string carried by the `hello_ack` vector.
const FW_VERSION_STR: &str = "2.0.0-test";
const FW_VERSION: &[u8] = FW_VERSION_STR.as_bytes();

/// Unassigned type byte used by the `cobs_boundary_254` vector — receivers
/// must parse it as [`Parsed::Unknown`] and ignore it.
const BOUNDARY_TYPE_BYTE: u8 = 0x7E;

/// Leading garbage of `resync.stream`: plausible line noise, deliberately
/// free of `0x00` so the first delimiter in the stream is the explicit one.
const RESYNC_GARBAGE: &[u8] = &[0xDE, 0xAD, 0xBE, 0xEF, 0x42, 0x13, 0x37];

struct PositiveVector {
    name: &'static str,
    ty: PacketType,
    purpose: &'static str,
}

const POSITIVE: &[PositiveVector] = &[
    PositiveVector {
        name: "hello",
        ty: PacketType::Hello,
        purpose: "host->device handshake open carrying the protocol version",
    },
    PositiveVector {
        name: "hello_ack",
        ty: PacketType::HelloAck,
        purpose:
            "device->host handshake reply: protocol version, 32x32 panel, fw_version 2.0.0-test",
    },
    PositiveVector {
        name: "brightness",
        ty: PacketType::Brightness,
        purpose: "brightness set-point 200 (0xC8)",
    },
    PositiveVector {
        name: "button_event_short",
        ty: PacketType::ButtonEvent,
        purpose: "device->host short press of button 0 (brightness up)",
    },
    PositiveVector {
        name: "button_event_long",
        ty: PacketType::ButtonEvent,
        purpose: "device->host long press of button 2 (sleep)",
    },
    PositiveVector {
        name: "frame",
        ty: PacketType::Frame,
        purpose: "full 32x32 RGB888 frame; deterministic piecewise payload (byte i): \
                  i<256 -> 0 if i%8==0 else i; i<512 -> 0xFF; i<1024 -> (i*7)%256; \
                  i<1342 -> (i%253)+1; else i%256. Contains zero bytes, a 257-byte 0xFF \
                  run (byte 255 is already 0xFF, then 256..=511), and non-zero runs \
                  longer than 254 bytes, so COBS group handling is exercised end to end",
    },
];

/// Error classes the negative vectors are allowed to name. These are the
/// cross-language contract classes — each implementation maps them onto
/// its own error type (Rust: `cobs::Error::Malformed`,
/// `packet::Error::BadCrc`, `packet::Error::BadLength`).
#[derive(Copy, Clone, Debug, PartialEq, Eq)]
enum ErrorClass {
    CobsMalformed,
    BadCrc,
    BadLength,
}

impl ErrorClass {
    fn manifest_name(self) -> &'static str {
        match self {
            ErrorClass::CobsMalformed => "cobs_malformed",
            ErrorClass::BadCrc => "bad_crc",
            ErrorClass::BadLength => "bad_length",
        }
    }
}

const ERROR_CLASSES: [ErrorClass; 3] = [
    ErrorClass::CobsMalformed,
    ErrorClass::BadCrc,
    ErrorClass::BadLength,
];

struct NegativeVector {
    name: &'static str,
    class: ErrorClass,
    purpose: &'static str,
}

const NEGATIVE: &[NegativeVector] = &[
    NegativeVector {
        name: "bad_crc",
        class: ErrorClass::BadCrc,
        purpose: "brightness packet whose payload byte was corrupted after the CRC was \
                  computed; COBS decodes cleanly, the CRC check must reject",
    },
    NegativeVector {
        name: "truncated",
        class: ErrorClass::CobsMalformed,
        purpose: "COBS group header promises 4 data bytes but only 2 are present before \
                  the delimiter; the COBS decoder must reject",
    },
    NegativeVector {
        name: "embedded_zero_garbage",
        class: ErrorClass::CobsMalformed,
        purpose: "a 0x00 inside COBS group data, which a valid encoder never produces; \
                  the COBS decoder must reject",
    },
    NegativeVector {
        name: "wrong_length_known_type",
        class: ErrorClass::BadLength,
        purpose: "valid CRC, known type Frame (0x02), but a 5-byte payload instead of \
                  3072; the typed layer must reject",
    },
];

const BOUNDARY_PURPOSE: &str =
    "raw form ends in exactly 254 non-zero bytes immediately after a zero byte, so a \
     canonical (Cheshire-Baker Listing 1) COBS encoder emits a full 0xFF group followed \
     by a trailing 0x01 group header before the delimiter. The Wikipedia cobsEncode \
     example omits that trailing 0x01; an encoder ported from it produces a wire one \
     byte shorter and must fail the byte-exact comparison against this vector. Type \
     byte 0x7E is unassigned, so receivers parse this packet as unknown and ignore it. \
     Exact raw bytes, re-derivable: [0x7E, 0x51, tweak, 0x00, 0x01, 0x02, .., 0xFC, \
     crc_lo, crc_hi] where tweak is the smallest value in 0x00..=0xFF for which \
     neither CRC-16/CCITT-FALSE byte of the whole preceding sequence is zero; in this \
     committed file tweak = 0x00, giving 252 ascending pattern bytes + 2 CRC bytes = 254 \
     zero-free trailing bytes after the 0x00 at raw offset 3";

const RESYNC_PURPOSE: &str =
    "garbage bytes containing no delimiter, then a lone 0x00, then hello.wire and \
     brightness.wire verbatim; a decoder walking the stream must drop the garbage \
     segment and recover exactly the two embedded packets in order";

const MANIFEST_DESCRIPTION: &str =
    "Cross-language golden vectors for the uniflag v2 binary protocol \
     (docs/protocol.md): the bytes the Rust and C# codecs are both checked \
     against. The Rust conformance suite (proto/tests/golden_vectors.rs) and \
     the C# plugin suite load these exact files; neither side generates its own \
     fixtures. Regenerate only via just golden-regen, and only on purpose: a \
     regen that moves bytes is a protocol change.";

const READING_RAW: &str =
    "type byte, then payload, then CRC-16/CCITT-FALSE (poly 0x1021, init 0xFFFF, no \
     reflection, xorout 0) computed over type+payload and appended little-endian";

const READING_WIRE: &str =
    "COBS-encoded raw followed by a single 0x00 delimiter; canonical Cheshire-Baker \
     Listing 1 encoding, meaning the encoder always terminates with a group header";

const READING_NEGATIVE: &str =
    "strip the single trailing 0x00 delimiter, then run the remaining bytes through \
     the decode pipeline (COBS decode, then CRC check, then typed parse); it must \
     fail with the error class named by the vector";

const READING_STREAM: &str =
    "split on 0x00 delimiters, run every non-empty segment through the decode \
     pipeline, drop segments that fail; the surviving packets must equal \
     expected_packets exactly and in order";

const GITATTRIBUTES: &str = "# Golden vectors are byte-exact cross-language fixtures.\n\
                             # Never eol-convert them (manifest.json has no NUL bytes, so\n\
                             # git would otherwise treat it as text under autocrlf).\n\
                             * -text\n";

// Deterministic builders — pure functions of the constants above.

/// Byte `i` of the 3072-byte frame payload. Piecewise so the framing layer
/// sees zero bytes, a long 0xFF run, and 254+ zero-free runs (the manifest
/// `purpose` for `frame` states the same formula in prose — keep in sync).
fn frame_pixel(i: usize) -> u8 {
    match i {
        0..=255 => {
            if i.is_multiple_of(8) {
                0
            } else {
                i as u8
            }
        }
        256..=511 => 0xFF,
        512..=1023 => ((i * 7) % 256) as u8,
        1024..=1341 => (i % 253) as u8 + 1,
        _ => (i % 256) as u8,
    }
}

fn frame_pixels() -> [u8; FRAME_PAYLOAD_LEN] {
    core::array::from_fn(frame_pixel)
}

/// The payload layout of each positive vector, written out longhand
/// and independently of [`Packet::encode`] so the tests cross-check the
/// two statements of the layout against each other.
fn payload_of(name: &str, pixels: &[u8; FRAME_PAYLOAD_LEN]) -> Vec<u8> {
    match name {
        "hello" => vec![PROTOCOL_VERSION],
        "hello_ack" => {
            let mut payload = vec![PROTOCOL_VERSION, PANEL_WIDTH as u8, PANEL_HEIGHT as u8];
            payload.extend_from_slice(FW_VERSION);
            payload
        }
        "brightness" => vec![BRIGHTNESS_VALUE],
        "button_event_short" => vec![Button::BrightnessUp.to_byte(), PressKind::Short.to_byte()],
        "button_event_long" => vec![Button::Sleep.to_byte(), PressKind::Long.to_byte()],
        "frame" => pixels.to_vec(),
        other => panic!("no payload defined for vector {other}"),
    }
}

/// The typed packet each positive vector must parse to.
fn expected_packet<'a>(name: &str, pixels: &'a [u8; FRAME_PAYLOAD_LEN]) -> Packet<'a> {
    match name {
        "hello" => Packet::Hello {
            protocol_version: PROTOCOL_VERSION,
        },
        "hello_ack" => Packet::HelloAck {
            protocol_version: PROTOCOL_VERSION,
            width: PANEL_WIDTH as u8,
            height: PANEL_HEIGHT as u8,
            fw_version: FW_VERSION,
        },
        "brightness" => Packet::Brightness {
            value: BRIGHTNESS_VALUE,
        },
        "button_event_short" => Packet::ButtonEvent {
            button: Button::BrightnessUp.to_byte(),
            kind: PressKind::Short.to_byte(),
        },
        "button_event_long" => Packet::ButtonEvent {
            button: Button::Sleep.to_byte(),
            kind: PressKind::Long.to_byte(),
        },
        "frame" => Packet::Frame { pixels },
        other => panic!("no expected packet for vector {other}"),
    }
}

/// Raw form (type + payload + CRC-16 LE) via the library encoder.
fn raw_of(ty: PacketType, payload: &[u8]) -> Vec<u8> {
    let mut out = vec![0u8; 1 + payload.len() + 2];
    let n = packet::write_raw(ty, payload, &mut out).expect("raw buffer sized exactly");
    out.truncate(n);
    out
}

/// Wire form: COBS(raw) plus the single trailing `0x00` delimiter.
fn wire_of_raw(raw: &[u8]) -> Vec<u8> {
    let mut out = vec![0u8; cobs::max_encoded_len(raw.len()) + 1];
    let n = cobs::encode(raw, &mut out).expect("wire buffer sized by max_encoded_len");
    out[n] = 0x00;
    out.truncate(n + 1);
    out
}

/// Raw form of the `cobs_boundary_254` vector: an unknown-type packet whose
/// raw bytes end in exactly 254 non-zero bytes (252 pattern bytes + 2 CRC
/// bytes) immediately after a `0x00`. The tweak byte deterministically
/// walks up from zero until neither CRC byte is zero, so the trailing run
/// is guaranteed zero-free; the first hit is what the committed file holds.
fn boundary_raw() -> Vec<u8> {
    for tweak in 0..=u8::MAX {
        let mut raw = vec![BOUNDARY_TYPE_BYTE, 0x51, tweak, 0x00];
        raw.extend(1..=252u8);
        let checksum = crc::checksum(&raw).to_le_bytes();
        if checksum[0] != 0 && checksum[1] != 0 {
            raw.extend_from_slice(&checksum);
            return raw;
        }
    }
    panic!("no tweak byte yields a zero-free CRC");
}

/// Wire bytes of each negative vector.
fn negative_wire(name: &str) -> Vec<u8> {
    match name {
        "bad_crc" => {
            let mut raw = raw_of(PacketType::Brightness, &[BRIGHTNESS_VALUE]);
            // Corrupt the payload byte after the CRC was computed. 0xC8 ^
            // 0xFF = 0x37 stays non-zero, so the COBS layer is untouched
            // and the corruption is visible only to the CRC check.
            raw[1] ^= 0xFF;
            wire_of_raw(&raw)
        }
        // Group header 0x05 promises 4 data bytes; only 2 arrive before
        // the delimiter.
        "truncated" => vec![0x05, 0x11, 0x22, 0x00],
        // Group header 0x04 promises 3 data bytes and gets them, but one
        // is an embedded 0x00 — never produced by a valid encoder.
        "embedded_zero_garbage" => vec![0x04, 0x41, 0x00, 0x42, 0x00],
        "wrong_length_known_type" => {
            wire_of_raw(&raw_of(PacketType::Frame, &[0x01, 0x02, 0x03, 0x04, 0x05]))
        }
        other => panic!("no negative wire defined for vector {other}"),
    }
}

/// `resync.stream`: garbage (no delimiter), a lone `0x00`, then the exact
/// bytes of `hello.wire` and `brightness.wire`.
fn resync_stream(pixels: &[u8; FRAME_PAYLOAD_LEN]) -> Vec<u8> {
    let mut stream = RESYNC_GARBAGE.to_vec();
    stream.push(0x00);
    stream.extend(wire_of_raw(&raw_of(
        PacketType::Hello,
        &payload_of("hello", pixels),
    )));
    stream.extend(wire_of_raw(&raw_of(
        PacketType::Brightness,
        &payload_of("brightness", pixels),
    )));
    stream
}

// Manifest rendering. Plain string building keeps `proto` free of a JSON
// dependency; `json_str` refuses anything that would need escaping.

fn json_str(value: &str) -> String {
    assert!(
        value
            .chars()
            .all(|c| c.is_ascii() && !c.is_ascii_control() && c != '"' && c != '\\'),
        "manifest string would need JSON escaping: {value}"
    );
    format!("\"{value}\"")
}

fn json_entry(fields: &[(&str, String)]) -> String {
    let body: Vec<String> = fields
        .iter()
        .map(|(key, value)| format!("      \"{key}\": {value}"))
        .collect();
    format!("    {{\n{}\n    }}", body.join(",\n"))
}

fn type_name(ty: PacketType) -> &'static str {
    match ty {
        PacketType::Hello => "Hello",
        PacketType::Frame => "Frame",
        PacketType::Brightness => "Brightness",
        PacketType::HelloAck => "HelloAck",
        PacketType::ButtonEvent => "ButtonEvent",
    }
}

/// The typed field values of a positive vector, as a JSON object the C#
/// suite can build its expectation from.
fn packet_fields_json(name: &str) -> String {
    match name {
        "hello" => format!(r#"{{ "protocol_version": {PROTOCOL_VERSION} }}"#),
        "hello_ack" => format!(
            r#"{{ "protocol_version": {PROTOCOL_VERSION}, "width": {PANEL_WIDTH}, "height": {PANEL_HEIGHT}, "fw_version": "{FW_VERSION_STR}" }}"#
        ),
        "brightness" => format!(r#"{{ "value": {BRIGHTNESS_VALUE} }}"#),
        "button_event_short" => format!(
            r#"{{ "button": {}, "kind": {} }}"#,
            Button::BrightnessUp.to_byte(),
            PressKind::Short.to_byte()
        ),
        "button_event_long" => format!(
            r#"{{ "button": {}, "kind": {} }}"#,
            Button::Sleep.to_byte(),
            PressKind::Long.to_byte()
        ),
        "frame" => {
            r#"{ "note": "payload is the 3072 pattern bytes; compare against raw[1..3073] verbatim" }"#
                .to_string()
        }
        other => panic!("no packet fields for vector {other}"),
    }
}

fn manifest_json() -> String {
    let mut vectors: Vec<String> = Vec::new();
    for v in POSITIVE {
        vectors.push(json_entry(&[
            ("name", json_str(v.name)),
            ("kind", json_str("packet")),
            ("packet_type", json_str(type_name(v.ty))),
            ("type_byte", v.ty.to_byte().to_string()),
            (
                "files",
                format!(r#"{{ "raw": "{0}.raw", "wire": "{0}.wire" }}"#, v.name),
            ),
            ("packet", packet_fields_json(v.name)),
            ("purpose", json_str(v.purpose)),
        ]));
    }
    vectors.push(json_entry(&[
        ("name", json_str("cobs_boundary_254")),
        ("kind", json_str("unknown_packet")),
        ("type_byte", BOUNDARY_TYPE_BYTE.to_string()),
        (
            "files",
            r#"{ "raw": "cobs_boundary_254.raw", "wire": "cobs_boundary_254.wire" }"#.to_string(),
        ),
        ("purpose", json_str(BOUNDARY_PURPOSE)),
    ]));
    for n in NEGATIVE {
        vectors.push(json_entry(&[
            ("name", json_str(n.name)),
            ("kind", json_str("negative")),
            ("error", json_str(n.class.manifest_name())),
            ("files", format!(r#"{{ "wire": "{}.wire" }}"#, n.name)),
            ("purpose", json_str(n.purpose)),
        ]));
    }
    vectors.push(json_entry(&[
        ("name", json_str("resync")),
        ("kind", json_str("resync")),
        ("files", r#"{ "stream": "resync.stream" }"#.to_string()),
        (
            "expected_packets",
            r#"[ "hello", "brightness" ]"#.to_string(),
        ),
        ("purpose", json_str(RESYNC_PURPOSE)),
    ]));

    let classes: Vec<String> = ERROR_CLASSES
        .iter()
        .map(|c| json_str(c.manifest_name()))
        .collect();

    let mut m = String::new();
    m.push_str("{\n");
    m.push_str("  \"format\": 1,\n");
    m.push_str(&format!("  \"protocol_version\": {PROTOCOL_VERSION},\n"));
    m.push_str(&format!(
        "  \"description\": {},\n",
        json_str(MANIFEST_DESCRIPTION)
    ));
    m.push_str("  \"reading\": {\n");
    m.push_str(&format!("    \"raw\": {},\n", json_str(READING_RAW)));
    m.push_str(&format!("    \"wire\": {},\n", json_str(READING_WIRE)));
    m.push_str(&format!(
        "    \"negative\": {},\n",
        json_str(READING_NEGATIVE)
    ));
    m.push_str(&format!("    \"stream\": {}\n", json_str(READING_STREAM)));
    m.push_str("  },\n");
    m.push_str(&format!(
        "  \"error_classes\": [ {} ],\n",
        classes.join(", ")
    ));
    m.push_str("  \"vectors\": [\n");
    m.push_str(&vectors.join(",\n"));
    m.push_str("\n  ]\n}\n");
    m
}

/// Every file under `testdata/proto/`, by name, with its expected content.
/// The single source both for [`regen`] and for the currency check.
fn all_files() -> Vec<(String, Vec<u8>)> {
    let pixels = frame_pixels();
    let mut files: Vec<(String, Vec<u8>)> = Vec::new();
    for v in POSITIVE {
        let raw = raw_of(v.ty, &payload_of(v.name, &pixels));
        files.push((format!("{}.wire", v.name), wire_of_raw(&raw)));
        files.push((format!("{}.raw", v.name), raw));
    }
    let braw = boundary_raw();
    files.push(("cobs_boundary_254.wire".to_string(), wire_of_raw(&braw)));
    files.push(("cobs_boundary_254.raw".to_string(), braw));
    for n in NEGATIVE {
        files.push((format!("{}.wire", n.name), negative_wire(n.name)));
    }
    files.push(("resync.stream".to_string(), resync_stream(&pixels)));
    files.push(("manifest.json".to_string(), manifest_json().into_bytes()));
    files.push((".gitattributes".to_string(), GITATTRIBUTES.into()));
    files
}

// Test plumbing.

fn testdata_dir() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join("testdata")
        .join("proto")
}

fn read_vector(name: &str) -> Vec<u8> {
    let path = testdata_dir().join(name);
    fs::read(&path).unwrap_or_else(|err| {
        panic!(
            "missing golden vector {} ({err}); regenerate via just golden-regen",
            path.display()
        )
    })
}

/// Byte-exact comparison with a diff-friendly failure message (offset of
/// the first difference instead of a multi-kilobyte hex dump).
fn assert_bytes_eq(context: &str, got: &[u8], want: &[u8]) {
    if got == want {
        return;
    }
    let offset = got
        .iter()
        .zip(want.iter())
        .position(|(a, b)| a != b)
        .unwrap_or(got.len().min(want.len()));
    panic!(
        "{context}: byte mismatch - got {} bytes, want {} bytes, first difference at \
         offset {offset} (got {:?}, want {:?})",
        got.len(),
        want.len(),
        got.get(offset),
        want.get(offset),
    );
}

/// The receiver-side decode pipeline the negative vectors are defined
/// against: strip the single trailing delimiter, COBS-decode, CRC-check,
/// typed-parse. Collapses the Rust error types onto the cross-language
/// [`ErrorClass`] contract; anything outside the contract panics.
fn classify(name: &str, wire: &[u8]) -> Result<(), ErrorClass> {
    assert_eq!(
        wire.last(),
        Some(&0x00),
        "{name}: missing trailing delimiter"
    );
    let body = &wire[..wire.len() - 1];
    let mut raw = vec![0u8; MAX_RAW_LEN];
    let raw_len = match cobs::decode(body, &mut raw) {
        Ok(n) => n,
        Err(cobs::Error::Malformed) => return Err(ErrorClass::CobsMalformed),
        Err(err) => panic!("{name}: unexpected COBS error {err:?}"),
    };
    match packet::parse_packet(&raw[..raw_len]) {
        Ok(_) => Ok(()),
        Err(packet::Error::BadCrc) => Err(ErrorClass::BadCrc),
        Err(packet::Error::BadLength) => Err(ErrorClass::BadLength),
        Err(err) => panic!("{name}: unexpected parse error {err:?}"),
    }
}

fn longest_run(bytes: &[u8], pred: impl Fn(u8) -> bool) -> usize {
    let mut best = 0usize;
    let mut current = 0usize;
    for &byte in bytes {
        if pred(byte) {
            current += 1;
            best = best.max(current);
        } else {
            current = 0;
        }
    }
    best
}

// Normal tests — run against the committed files on disk.

/// Every file on disk is byte-identical to its generator, and the
/// directory holds nothing else. Because manifest.json is one of those
/// files, this also proves the manifest matches the vector tables that
/// drive every other test here.
#[test]
fn vector_files_are_current_and_complete() {
    let files = all_files();
    for (name, want) in &files {
        let got = read_vector(name);
        assert_bytes_eq(&format!("testdata/proto/{name}"), &got, want);
    }
    let expected: BTreeSet<String> = files.iter().map(|(name, _)| name.clone()).collect();
    let mut on_disk = BTreeSet::new();
    for entry in fs::read_dir(testdata_dir()).expect("read testdata/proto") {
        let entry = entry.expect("directory entry");
        on_disk.insert(entry.file_name().to_string_lossy().into_owned());
    }
    assert_eq!(
        on_disk, expected,
        "stray or missing files in testdata/proto"
    );
}

/// The on-disk manifest references every vector file by name (belt and
/// braces on top of the byte-identity check above, and it reads the
/// manifest from disk the way the C# suite will).
#[test]
fn manifest_references_every_vector_file() {
    let manifest = String::from_utf8(read_vector("manifest.json")).expect("manifest is UTF-8");
    for (name, _) in all_files() {
        if name == "manifest.json" || name == ".gitattributes" {
            continue;
        }
        assert!(
            manifest.contains(&format!("\"{name}\"")),
            "manifest.json does not reference {name}"
        );
    }
}

#[test]
fn raw_vectors_parse_to_the_expected_typed_packet() {
    let pixels = frame_pixels();
    for v in POSITIVE {
        let raw = read_vector(&format!("{}.raw", v.name));
        let expected = expected_packet(v.name, &pixels);
        match packet::parse_packet(&raw) {
            Ok(Parsed::Known(parsed)) => assert_eq!(parsed, expected, "{}", v.name),
            other => panic!("{}: expected a Known packet, got {other:?}", v.name),
        }
    }
}

#[test]
fn raw_vectors_reencode_byte_identically() {
    let pixels = frame_pixels();
    for v in POSITIVE {
        let raw = read_vector(&format!("{}.raw", v.name));
        let rebuilt = raw_of(v.ty, &payload_of(v.name, &pixels));
        assert_bytes_eq(&format!("{}.raw re-encode", v.name), &rebuilt, &raw);
    }
}

#[test]
fn wire_vectors_decode_parse_and_reencode_byte_identically() {
    let pixels = frame_pixels();
    for v in POSITIVE {
        let name = v.name;
        let wire = read_vector(&format!("{name}.wire"));
        let raw_file = read_vector(&format!("{name}.raw"));

        assert_eq!(wire.last(), Some(&0x00), "{name}: missing delimiter");
        let body = &wire[..wire.len() - 1];
        assert!(!body.contains(&0x00), "{name}: 0x00 inside the COBS body");

        let mut raw = vec![0u8; MAX_RAW_LEN];
        let raw_len = cobs::decode(body, &mut raw)
            .unwrap_or_else(|err| panic!("{name}: COBS decode failed: {err:?}"));
        assert_bytes_eq(
            &format!("{name}: decoded wire body"),
            &raw[..raw_len],
            &raw_file,
        );

        let expected = expected_packet(name, &pixels);
        match packet::parse_packet(&raw[..raw_len]) {
            Ok(Parsed::Known(parsed)) => assert_eq!(parsed, expected, "{name}"),
            other => panic!("{name}: expected a Known packet, got {other:?}"),
        }
        assert_eq!(classify(name, &wire), Ok(()), "{name}: decode pipeline");

        let mut scratch = vec![0u8; MAX_RAW_LEN];
        let mut out = vec![0u8; MAX_WIRE_LEN];
        let wire_len = expected
            .encode(&mut scratch, &mut out)
            .unwrap_or_else(|err| panic!("{name}: typed encode failed: {err:?}"));
        assert_bytes_eq(
            &format!("{name}.wire typed re-encode"),
            &out[..wire_len],
            &wire,
        );
    }
}

/// The frame payload actually stresses what it claims to: zero bytes, a
/// 254+ run of 0xFF, and a 254+ zero-free run — asserted on the file
/// bytes, not the generator.
#[test]
fn frame_vector_payload_stresses_cobs() {
    let raw = read_vector("frame.raw");
    let payload = &raw[1..raw.len() - 2];
    assert_eq!(payload.len(), FRAME_PAYLOAD_LEN);
    assert!(payload.contains(&0x00), "frame payload has no zero bytes");
    let ff_run = longest_run(payload, |b| b == 0xFF);
    assert!(ff_run >= 254, "longest 0xFF run is only {ff_run}");
    let nonzero_run = longest_run(payload, |b| b != 0);
    assert!(
        nonzero_run >= 254,
        "longest zero-free run is only {nonzero_run}"
    );
}

#[test]
fn cobs_boundary_254_raw_ends_in_254_nonzero_bytes_after_a_zero() {
    let raw = read_vector("cobs_boundary_254.raw");
    assert_bytes_eq("cobs_boundary_254.raw", &raw, &boundary_raw());

    let boundary = raw.len() - 255;
    assert_eq!(raw[boundary], 0x00, "no zero before the trailing run");
    assert!(
        raw[boundary + 1..].iter().all(|&b| b != 0),
        "the trailing 254 bytes must be zero-free"
    );

    // Valid CRC, unassigned type: parses as Unknown for caller-side
    // ignoring — never an error.
    match packet::parse_packet(&raw) {
        Ok(Parsed::Unknown { ty, payload }) => {
            assert_eq!(ty, BOUNDARY_TYPE_BYTE);
            assert_eq!(payload, &raw[1..raw.len() - 2]);
        }
        other => panic!("expected an Unknown packet, got {other:?}"),
    }
}

#[test]
fn cobs_boundary_254_wire_is_the_canonical_listing_1_form() {
    let wire = read_vector("cobs_boundary_254.wire");
    let raw_file = read_vector("cobs_boundary_254.raw");
    let len = wire.len();

    assert_eq!(wire[len - 1], 0x00, "missing delimiter");
    assert_eq!(
        wire[len - 2],
        0x01,
        "canonical trailing group header missing (Wikipedia-variant encoder?)"
    );
    assert_eq!(
        wire[len - 257],
        0xFF,
        "expected a full 254-byte group before the trailing header"
    );

    let mut raw = vec![0u8; MAX_RAW_LEN];
    let n = cobs::decode(&wire[..len - 1], &mut raw).expect("COBS decode");
    assert_bytes_eq("cobs_boundary_254 decoded wire body", &raw[..n], &raw_file);

    let rebuilt = wire_of_raw(&raw_file);
    assert_bytes_eq("cobs_boundary_254.wire re-encode", &rebuilt, &wire);

    // The non-canonical (Wikipedia) form — the same bytes minus the
    // trailing 0x01 header — decodes to the identical raw packet. That
    // round-trip blindness is exactly why only the byte-exact comparison
    // against this committed wire catches a Wikipedia-derived encoder port.
    let mut raw2 = vec![0u8; MAX_RAW_LEN];
    let m = cobs::decode(&wire[..len - 2], &mut raw2).expect("decode non-canonical form");
    assert_bytes_eq(
        "non-canonical form must decode identically",
        &raw2[..m],
        &raw_file,
    );
}

#[test]
fn negative_vectors_fail_with_exactly_the_expected_class() {
    for n in NEGATIVE {
        let wire = read_vector(&format!("{}.wire", n.name));
        assert_eq!(classify(n.name, &wire), Err(n.class), "{}", n.name);
    }
}

#[test]
fn resync_stream_recovers_exactly_the_embedded_packets() {
    let stream = read_vector("resync.stream");

    // Layout: garbage (delimiter-free), a lone 0x00, then the on-disk
    // hello.wire and brightness.wire verbatim.
    assert!(
        !RESYNC_GARBAGE.contains(&0x00),
        "garbage must not contain a delimiter"
    );
    let mut expected_stream = RESYNC_GARBAGE.to_vec();
    expected_stream.push(0x00);
    expected_stream.extend_from_slice(&read_vector("hello.wire"));
    expected_stream.extend_from_slice(&read_vector("brightness.wire"));
    assert_bytes_eq("resync.stream layout", &stream, &expected_stream);

    // Walk the stream the way a receiver does: split on 0x00, feed each
    // non-empty segment through COBS + parse, drop failures.
    let mut recovered: Vec<Vec<u8>> = Vec::new();
    for segment in stream.split(|&b| b == 0x00) {
        if segment.is_empty() {
            continue;
        }
        let mut raw = vec![0u8; MAX_RAW_LEN];
        let Ok(n) = cobs::decode(segment, &mut raw) else {
            continue;
        };
        if packet::parse_packet(&raw[..n]).is_ok() {
            recovered.push(raw[..n].to_vec());
        }
    }

    assert_eq!(recovered.len(), 2, "expected exactly two recovered packets");
    assert_eq!(
        packet::parse_packet(&recovered[0]),
        Ok(Parsed::Known(Packet::Hello {
            protocol_version: PROTOCOL_VERSION
        }))
    );
    assert_eq!(
        packet::parse_packet(&recovered[1]),
        Ok(Parsed::Known(Packet::Brightness {
            value: BRIGHTNESS_VALUE
        }))
    );
}

// Regeneration — deliberately #[ignore]d so it never runs as a test side
// effect. Only `just golden-regen` invokes it, via
// `cargo test -p proto --test golden_vectors -- --ignored regen`.

#[test]
#[ignore = "rewrites the golden vectors; run only via just golden-regen"]
fn regen() {
    let dir = testdata_dir();
    fs::create_dir_all(&dir).expect("create testdata/proto");
    for (name, bytes) in all_files() {
        fs::write(dir.join(&name), &bytes)
            .unwrap_or_else(|err| panic!("write testdata/proto/{name}: {err}"));
    }
}
